name: Multipy runtime nightly test + release

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  pull_request:
  push:
    branches:
      - main


jobs:
  unittest:
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']
        platform: [ubuntu-18.04]
        runner_dir: [$RUNNER_TEMP] #needed since releaser has trouble parsing env variables
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout MultiPy
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup SSH (Click me for login details)
        uses: ./.github/actions/setup-ssh
        with:
          github-secret: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        env:
          DOCKER_BUILDKIT: 1
        run: docker build -t multipy --progress=plain --build-arg PYTHON_VERSION=${{ matrix.python-version }} .

      - name: Create Tarball
        run: |
          cd $RUNNER_TEMP
          docker cp $(docker run -d multipy):/opt/dist/multipy .
          tar -czvf multipy_runtime.tar.gz multipy/

      - name: Update nightly release
        uses: pyTooling/Actions/releaser@main
        with:
          tag: nightly-runtime-python${{ matrix.python-version }}
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ${{matrix.runner_dir}}/multipy_runtime.tar.gz
